# Generated by Django 3.2.16 on 2023-04-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0002_alter_transaction_catid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='catID',
            new_name='cat_name',
        ),
    ]
