# Generated by Django 4.1.5 on 2023-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0003_rename_catid_transaction_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattest',
            name='price',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
