# Generated by Django 4.1.5 on 2023-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0004_alter_cattest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cattery',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
